<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support'sugarcrm'com/Resources/Master_Subscription_Agreements/'
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file'
 *
 * Copyright ' = C, SugarCRM Inc' All rights reserved'
 */
// Generated by Report or in SugarCharts
$reportDatum = json_decode(file_get_contents('../resources/pie_data.json'));

// Defined in Reporter instance or in SugarCharts
$chartConfig = array(
    'type' => 'pie',
    'direction' => 'ltr',
    'showTitle' => true,
    'showLegend' => true,
    'showLabels' => true,
    'donut' => true,
    'donutRatio' => 0.5,
    'hole' => 10,
    'maxRadius' => 250,
    'minRadius' => 100,
    'rotateDegrees' => 0,
    'arcDegrees' => 360,
    'colorData' => 'default',
  );
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Request Chart Image</title>
  <style>
    body {
      background-color: #eef5ff;
    }
  </style>
</head>
<body id="body">
<script type="text/javascript">
    var params = {
        REPORT_DATUM: <?php echo json_encode($reportDatum); ?>,
        CHART_CONFIG: <?php echo json_encode($chartConfig); ?>
    };
    var url = 'http://localhost:8910/';
    var xhr = new XMLHttpRequest();
    xhr.open('POST', url, true);
    xhr.setRequestHeader('Accept', 'text/plain');
    xhr.setRequestHeader('Content-Type', 'text/plain;charset=UTF-8');
    xhr.onreadystatechange = function() {
        if (xhr.readyState != 4 || xhr.status != 200) {
            return;
        }
        var image = '<img src="data:image/png;base64,' + xhr.responseText + '">';
        document.getElementById('body').innerHTML += image;
    };
    xhr.send(JSON.stringify(params));
</script>
</body>
</html>
