<!--
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support'sugarcrm'com/Resources/Master_Subscription_Agreements/'
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file'
 *
 * Copyright ' = C, SugarCRM Inc' All rights reserved'
 */
-->
<?php
// Generated by Report or in SugarCharts
$reportDatum = json_decode(file_get_contents('resources/pie_data.json'));

// Defined in Reporter instance or in SugarCharts
$chartConfig = array(
    'type' => 'pie',
    'direction' => 'ltr',
    'showTitle' => true,
    'showLegend' => true,
    'showLabels' => true,
    'donut' => true,
    'donutRatio' => 0.5,
    'hole' => 10,
    'maxRadius' => 250,
    'minRadius' => 100,
    'rotateDegrees' => 0,
    'arcDegrees' => 360,
    'colorData' => 'default',
  );
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Request Chart Image</title>
</head>
<body>

<script src="resources/jquery-min.js"></script>

<script type="text/javascript">

  $(function() {
    var url = 'http://localhost/phantom2png/service.php';

    var data = {
      REPORT_DATUM: <?php echo json_encode($reportDatum); ?>,
      CHART_CONFIG: <?php echo json_encode($chartConfig); ?>
    };

    $.ajax({
      type: 'POST',
      url: url,
      data: data,
      success: function(response) {
        // Do with data as you like
        $('body').append('<img src="data:image/png;base64,' + response + '">');
      }
    });
  });

</script>

</body>
</html>
