apiVersion: v1
kind: Service
metadata:
  name: report2chart 
  labels:
    app: report2chart
spec:
  type: NodePort
  ports:
  - name: report2chart 
    port: 80 
    protocol: TCP
  selector:
    app: report2chart
