apiVersion: v1
kind: Service
metadata:
  name: tools 
  labels:
    app: tools
spec:
  type: NodePort
  ports:
  - name: tools
    port: 80 
    protocol: TCP
  selector:
    app: tools
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: tools
spec:
  type: NodePort
  ports:
  - name: ui
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: tools
