apiVersion: v1
kind: Service
metadata:
  name: report2chart
  labels:
    pipeline.sugarcrm.io/app: report2chart
    pipeline.sugarcrm.io/commit: %%VERSION%%
spec:
  ports:
  - name: service
    port: 80 
    protocol: TCP
  selector:
    pipeline.sugarcrm.io/app: report2chart
    pipeline.sugarcrm.io/commit: %%VERSION%%
